name: stirling-pdf

services:
  stirling-pdf:
    image: ghcr.io/stirling-tools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "40005:8080"
    volumes:
      - ./trainingData:/usr/share/tesseract-ocr-4.00/tessdata
      - ./extraConfigs:/configs
    env_file:
      - pdf-editor-stirling.env
    networks:
      - edge
    restart: unless-stopped

networks:
  edge:
    external: true