name: navidrome

services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "30003:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "___REPLACE_ME_NAVIDROME_DATA_PATH___:/data"
      - "___REPLACE_ME_NAVIDROME_MUSIC_PATH___:/music:ro"
    networks:
      - edge

networks:
  edge:
    external: true